### ISSUE TITLE
Create new directory for post processing data

### ISSUE THREAD

**Issue by uniomni** [uniomni/PyARR#2]
Currently post processing data is stored with the raw input data making it difficult to clean out and rerun.
Suggest making a new director for post processing data which can easily be deleted without affecting the raw input data.

**Comment by uniomni** [comment]
Fixed in commit: https://github.com/uniomni/PyARR/commit/bfd276fb95e1270c7c787b5ab0706fa73e0f835f

**Comment by Dr-Shoznum** [comment]
did git pull

i get this error


('data_directory', '/home/petar/media/petar/TOSHIBA EXT/PyARR-data/1%AEP/')
('proc_directory', '/home/petar/media/petar/TOSHIBA
EXT/PyARR-postprocessed-data/1%AEP/')
Postprocessing storm 1 for quantity WL at all specified locations
Traceback (most recent call last):
  File "2_critical_duration_patterns.py", line 17, in <module>
    points_dict = post_process(durations=durations, locations=locations,
storm=storm, quantity=quantity, proc_directory=proc_directory,
blockage=blockage)
  File "/home/petar/PyARR/ARR2019_post_processing.py", line 198, in
post_process
    points_dict = critical_duration_pattern(fromdir, locations)
  File "/home/petar/PyARR/ARR2019_post_processing.py", line 142, in
critical_duration_pattern
    mean, (one_up_filename, value) = find_average_element(filename_list)
  File "/home/petar/PyARR/ARR2019_post_processing.py", line 68, in
find_average_element
    raise BaseException('Got an empty list: %s' % filename_list)
BaseException: Got an empty list: []


------------------
(program exited with code: 1)
Press return to continue

**Comment by uniomni** [comment]
Looks like your proc directory directory has a newline in it?

**Comment by uniomni** [comment]
I think this means the data hasn't been processed for that duration. It fails for me as well if I go past the processed data.

**Comment by uniomni** [comment]
Just added some diagnostics. We also need a better error message for this situation.

**Comment by Dr-Shoznum** [comment]
still cant get it. my data is all processed from 10 min to 2160min. really
weird.

Im getting tired, will leave it till tomorrow.
